-- ============================================================
-- Seed 002: Produtos com referência MakerWorld
-- Imagens via CDN hotlink (makerworld.bblmw.com) — ilustrativas.
-- Quando a empresa tiver foto própria: UPDATE product_images SET url = '...'
-- e UPDATE products SET makerworld_url = NULL WHERE slug = '...';
-- ============================================================

-- ============================================================
-- DECORAÇÃO
-- ============================================================
INSERT INTO products (name, slug, description, price, print_time_minutes, filament_grams, is_available, is_featured, allows_custom_color, allows_custom_size, category_id, makerworld_url) VALUES
('Vaso Fiori Espiral',        'vaso-fiori-espiral',        'Vaso decorativo com design único em espiral. Disponível em diversas cores vibrantes para decorar qualquer ambiente.',                                      45.00, 180, 80,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/1102758-flower-vase'),
('Vasos Japandi',             'vasos-japandi',             'Conjunto de vasos onde o estilo japonês encontra o escandinavo. Peça grande: 220 mm de altura, perfeita para flores secas.',                              55.00, 220, 95,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/964016-japandi-vases'),
('Vaso Clicker – The Last of Us', 'vaso-clicker-tlou',    'Porta-vaso inspirado no icônico Clicker de The Last of Us. Decoração geek e funcional para plantas pequenas.',                                            65.00, 240, 110, true, false, true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/1367333-clicker-the-last-of-us-porta-vaso'),
('Castiçal Anjo Guardião',    'castichal-anjo-guardiao',   'Escultura de castiçal com asas de anjo e mãos abertas. Design elegante para velas de até 5 cm de diâmetro.',                                               75.00, 300, 130, true, false, true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/1682199-guardian-flame-angelic-candle-holder-sculpture'),
('Luminária Pendente Art Déco','luminaria-art-deco',       'Cúpula geométrica Art Déco dos anos 1920. Imprime em modo vaso, encaixe para lâmpada E27 incluso.',                                                        85.00, 360, 150, true, false, true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/172453-art-deco-pendant-lamp-hanging-light'),
('Vaso Pixelado Cúbico',      'vaso-pixelado-cubico',      'Vaso com textura de pixels cúbicos — estética retro e moderna ao mesmo tempo. Disponível com ou sem furo de drenagem.',                                    40.00, 150, 65,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/1377817-cubic-pixelated-vase-3d-printable-planter'),
('Vaso Orgânico Texturizado',  'vaso-organico-texturizado', 'Vaso com superfície inflada de aspecto têxtil e orgânico. Elegante e moderno para decorar salas e varandas.',                                              48.00, 180, 80,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/452212-inflated-soft-cloth-planter-plant-pot-vase-series6'),
('Vaso Geométrico de Linhas',  'vaso-geometrico-linhas',    'Design minimalista com linhas geométricas paralelas. Ideal para suculentas e plantas pequenas em modo vaso.',                                              42.00, 160, 70,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/1339571-line-plant-pot-and-planter-vase-mode-design'),
('Vaso Personalizado Tamanho Ideal', 'vaso-tamanho-ideal', 'Gerador de vasos com espessura ideal e sistema de drenagem profissional. Escolha o tamanho que precisar.',                                                 50.00, 200, 85,  true, false, true, true,  (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/2172464-your-ideal-planter-customizable-size'),
('Vaso Elegante Minimalista',  'vaso-elegante-minimalista', 'Vaso de linhas limpas e design sofisticado. Perfeito para flores artificiais ou secas em ambientes minimalistas.',                                          38.00, 140, 60,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'decoracao'), 'https://makerworld.com/en/models/1031828-vaso-elegante')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- UTILITÁRIOS
-- ============================================================
INSERT INTO products (name, slug, description, price, print_time_minutes, filament_grams, is_available, is_featured, allows_custom_color, allows_custom_size, category_id, makerworld_url) VALUES
('Organizador de Cabos Portátil',   'organizador-cabos-portatil',    'Enrolador de cabos portátil com botão de fixação. Disponível em três tamanhos para diferentes comprimentos.',               25.00, 60,  18,  true, true,  true, true,  (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/13849-portable-cable-organizer-winder'),
('Organizador de Cabos',            'organizador-cabos',             'Clip elegante para manter cabos organizados e sem nós. Simples e eficaz no dia a dia.',                                      18.00, 45,  12,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/675366-cable-organizer'),
('Suporte de Cabos com Grampo',     'suporte-cabos-grampo',          'Suporte de cabos com grampo para fixar na mesa. Mantém cabos acessíveis sem bagunça.',                                       22.00, 50,  15,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/2001262-desk-cable-holder-cable-organizer-with-clamp'),
('Clips Organizadores de Cabos',    'clips-organizadores-cabos',     'Kit de clips em vários tamanhos para organizar cabos de celular, USB e outros. Liberação rápida pressionando as laterais.',  15.00, 30,  8,   true, false, true, true,  (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/1944124-cable-clip-cable-organizer-multiple-sizes'),
('Organizador de Cabos Minimalista','organizador-cabos-minimalista', 'Design limpo e discreto para manter cabos enrolados no bolso ou na bolsa. Perfeito para viagens.',                           20.00, 40,  10,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/462751-minimalistic-cable-organizer'),
('Organizador de Cabos Ergonômico', 'organizador-cabos-ergonomico',  'Forma anatômica que facilita enrolar e desenrolar cabos sem esforço. Ideal para carregadores e fones.',                      22.00, 50,  14,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/1166375-ergonomic-cable-organizer'),
('Organizador de Carregadores',     'organizador-carregadores',      'Versão final para organizar cabos carregadores de celular e USB. Design polido com encaixes precisos.',                      24.00, 55,  16,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/1999805-charger-cable-organizer-final-edition'),
('Suporte de Escova Dental Mural',  'suporte-escova-dental-mural',   'Suporte de parede com bandeja anti-gotejamento para duas escovas. Perfeito para casais e banheiros pequenos.',              20.00, 60,  22,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/392866-quip-toothbrush-holder-wall-mount-with-drip-tray'),
('Suporte Mural para Sabonete Líquido', 'suporte-sabonete-mural',    'Suporte de parede compatível com dispensers comuns. Mantém o sabonete fixo sem escorrer.',                                  22.00, 65,  24,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/251909-dettol-soap-dispenser-wall-mount'),
('Porta-Escova de Dentes de Parede','porta-escova-parede',           'Suporte mural para uma ou duas escovas. Instalação fácil, base com drenagem para higiene.',                                 18.00, 55,  20,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/1012342-toothbrush-wall-holder'),
('Porta-Utensílios de Cozinha Mural','porta-utensilios-cozinha',     'Suporte de parede para espátulas, colheres e facas. Libera espaço no balcão e deixa a cozinha organizada.',                 35.00, 90,  40,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/78390-kitchen-utensil-holder-wall-mounted-mise-en-place'),
('Porta-Copos com Suporte Mural',   'porta-copos-suporte-mural',     'Suporte mural com xícara removível para escovas e pequenos acessórios de banheiro. Fácil de higienizar.',                   20.00, 60,  22,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'utilitarios'), 'https://makerworld.com/en/models/1024165-wall-mounted-toothbrush-cup-holder')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- ESCRITÓRIO
-- ============================================================
INSERT INTO products (name, slug, description, price, print_time_minutes, filament_grams, is_available, is_featured, allows_custom_color, allows_custom_size, category_id, makerworld_url) VALUES
('Organizador de Mesa Escritório',       'org-mesa-escritorio',          'Organizador clássico com textura ribbed para canetas, tesouras, bloco de notas e gadgets.',                                             55.00, 240, 110, true, true,  true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/1313992-office-desk-organizer'),
('Suporte Celular + Porta-Caneta',       'suporte-celular-porta-caneta', 'Combinação de suporte para smartphone e porta-caneta em design IKEA-inspired. Compacto e elegante.',                                   45.00, 180, 80,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/847980-phone-stand-pen-holder-ikea-inspired-organizer'),
('Organizador com Dock para Celular',    'org-dock-celular',             'Organizador de mesa com dock para celular, compartimento para canetas e espaço para post-its.',                                          48.00, 200, 90,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/999714'),
('Organizador Mesa com Suporte',         'org-mesa-suporte',             'Design limpo com suporte para celular em ângulo confortável para leitura e videochamadas.',                                              52.00, 210, 95,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/1271917-desk-organizer-with-phone-stand'),
('Organizador com Gaveta e Dock',        'org-gaveta-dock',              'Organizador com gaveta oculta e suporte para celular. Guarda pequenos itens como clipes, borrachas e cartões.',                          65.00, 300, 130, true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/864633'),
('Organizador com Suporte Integrado',    'org-suporte-integrado',        'Suporte para celular integrado compatível com todos os tamanhos de smartphone. Múltiplos compartimentos.',                                58.00, 250, 110, true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/1726061-office-desk-organizer-with-integrated-phone-holder'),
('Sistema Modular iPhone + Canetas',     'sistema-modular-iphone',       'Kit modular: suporte iPhone, porta-caneta, copo de armazenamento e bandeja base. Configure como quiser.',                                75.00, 360, 160, true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/2087519-modular-desk-organizer-system-iphone-stand-module'),
('Organizador Slim com Dock',            'org-slim-dock',                'Versão slim e elegante de organizador com dock para celular. Ocupa pouco espaço, máxima funcionalidade.',                                44.00, 170, 75,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/898205'),
('Organizador Magnético Modular',        'org-magnetico-modular',        'Sistema magnético para organizar celular e canetas com arranjos intercambiáveis no seu espaço.',                                         70.00, 320, 140, true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/647758-magnetic-desk-organizer-modular-phone-pen-set'),
('Organizador Design Moderno',           'org-design-moderno',           'Compartimentos para canetas, cola, celular e cabos. Compatível com smartphones grandes como o iPhone 15 Max.',                           50.00, 220, 100, true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/701020-modern-design-organizer-with-phone-stand-w-o-ams'),
('Organizador com 3 Gavetas',            'org-3-gavetas',                'Três gavetas compactas em design minimalista para itens pequenos de papelaria e acessórios de escritório.',                              72.00, 340, 150, true, false, true, false, (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/2500817-office-desk-organizer-3-drawer-storage'),
('Organizadores Empilháveis',            'organizadores-empilaveis',     'Módulos empilháveis que crescem conforme sua necessidade. Estrutura, clareza e harmonia visual para qualquer mesa.',                     45.00, 190, 85,  true, false, true, true,  (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/2021917-stackable-organizers-for-office-home-workspace'),
('Sistema Modular Personalizado',        'sistema-modular-personalizado','Sistema de organização por dovetail joint — módulos que se encaixam e permitem layouts personalizados.',                                 80.00, 400, 180, true, false, true, true,  (SELECT id FROM categories WHERE slug = 'escritorio'), 'https://makerworld.com/en/models/2430667-modular-custom-office-desk-organizer-system')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- GAMES
-- ============================================================
INSERT INTO products (name, slug, description, price, print_time_minutes, filament_grams, is_available, is_featured, allows_custom_color, allows_custom_size, category_id, makerworld_url) VALUES
('Suporte Xbox + Fone de Ouvido',        'suporte-xbox-headphone',       'Suporte moderno para controle Xbox e headphone. Imprime em uma placa em aprox. 3 horas, sem suporte.',                                   65.00, 180, 80,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/1391837-xbox-controller-and-headphone-stand'),
('Suporte Gamer Futurista',              'suporte-gamer-futurista',      'Suporte com design futurista para headset e controles. Compatible com a maioria dos headsets do mercado.',                                75.00, 220, 100, true, true,  true, false, (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/1048970-futuristic-gaming-headset-controller-stand'),
('Suporte para Headset com Bandeja',     'suporte-headset-bandeja',      'Segura o headset no topo e tem bandeja na base para fones TWS, relógio ou acessórios pequenos.',                                          55.00, 200, 90,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/895748-headphone-stand-headset-holder-with-tray'),
('Torre de Games com Pegboard',          'torre-games-pegboard',         'Torre de armazenamento para jogos de Switch, PS4/PS5 e Xbox com pegboard lateral para acessórios.',                                       85.00, 420, 190, true, false, true, true,  (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/1934546-game-tower-with-skadis-pegboard'),
('Torre de Games Empilhável',            'torre-games-empilaveis',       'Torre infinitamente empilhável para jogos PS3/PS4/PS5, Xbox e Nintendo Switch. Cresce com sua coleção.',                                  70.00, 350, 155, true, false, true, true,  (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/817122-games-tower-v2-video-games-storage-stackable'),
('Porta de Masmorra – DnD',             'porta-masmorra-dnd',           'Porta de masmorra para cenários de RPG de mesa. Pedras detalhadas com grade de ferro e estética grimdark.',                               45.00, 240, 110, true, false, true, false, (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/1168182-dungeon-door-gate-dnd-scatter-terrain'),
('Torre de Dados Castelo Medieval',      'torre-dados-castelo',          'Torre de dados com design de castelo medieval. Funcional e decorativa para sessões de RPG e board games.',                                 60.00, 300, 135, true, false, true, false, (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/806414-medieval-castle-dice-tower'),
('Torre de Dados Isengard – LOTR',       'torre-dados-isengard',         'Torre de dados inspirada em Isengard do Senhor dos Anéis. Para os fãs de Tolkien que jogam RPG.',                                         65.00, 320, 145, true, false, true, false, (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/175425-lotr-isengard-dice-tower'),
('Torre de Dados de Viagem',             'torre-dados-viagem',           'Torre de dados simples e compacta, perfeita para levar em qualquer lugar. Fundo magnético e base removível.',                             35.00, 150, 65,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/110167'),
('Torre de Dados Caveira Fantasia',      'torre-dados-caveira',          'Torre de dados com caveira e tentáculos — tema horror-fantasia perfeito para DnD e jogos de terror.',                                     55.00, 280, 125, true, false, true, false, (SELECT id FROM categories WHERE slug = 'games'), 'https://makerworld.com/en/models/1540135-skull-dice-tower-with-tentacles-fantasy-diorama')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- BONECOS & COLECIONÁVEIS
-- ============================================================
INSERT INTO products (name, slug, description, price, print_time_minutes, filament_grams, is_available, is_featured, allows_custom_color, allows_custom_size, category_id, makerworld_url) VALUES
('Dragão Floppy Flexi Articulado',       'dragao-floppy-flexi',          'Dragão articulado print-in-place. Consegue ficar de pé, abrir a boca e mexer as asas. Zero montagem.',                                    45.00, 200, 90,  true, true,  true, true,  (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/769341-floppy-dragon-flexi-articulated-monster-pip'),
('Dragão Rise com Imãs',                 'dragao-rise-imas',             'Dragão articulado com suporte magnético. Pose dramática impressionante para exibir na estante.',                                           65.00, 300, 135, true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/854179'),
('Banguela Night Fury Articulado',       'banguela-night-fury',          'Reprodução articulada de Banguela, o Night Fury de Como Treinar o Seu Dragão. Print-in-place.',                                            55.00, 240, 110, true, true,  true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/1646485-flexi-toothless-night-fury-dragon-articulated-toy'),
('Dragão de Cristal Articulado',         'dragao-cristal-articulado',    'Dragão transparente com escamas detalhadas e junta articulada em cada segmento do corpo.',                                                 60.00, 270, 120, true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/55289-articulated-crystal-dragon-by-saber3d'),
('Shenron Articulado – Dragon Ball',     'shenron-dragon-ball',          'Shenron flexi totalmente articulado, sem suporte necessário. Perfeito para fãs de Dragon Ball Z.',                                         70.00, 330, 150, true, true,  true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/2446240-shenron-flexy-articulated-dragon'),
('Rathalos – Monster Hunter Dragon',     'rathalos-monster-hunter',      'Rathalos flexi articulado do universo Monster Hunter. Detalhamento impressionante para colecionadores.',                                   75.00, 360, 160, true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/1183669-rathalos-flexi-articulated-monster-hunter-dragon'),
('Dragão Fofo Articulado',               'dragao-fofo-articulado',       'Versão chibi adorável de dragão articulado. Ideal para presente e para quem quer algo fofinho e detalhado.',                               40.00, 180, 80,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/2196432-flexi-cute-dragon'),
('Stormtrooper – Star Wars',             'stormtrooper-star-wars',       'Stormtrooper Imperial com armadura detalhada e rifle blaster. Para colecionadores e fãs de Star Wars.',                                    65.00, 300, 135, true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/1174730-star-wars-imperial-stormtrooper'),
('MaidTrooper – Star Wars',              'maidtrooper-star-wars',        'Figurine de Stormtrooper com visual exclusivo. Edição especial para fãs que gostam de versões criativas.',                                 65.00, 300, 135, true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/1824036-maidtrooper-star-wars-figurine'),
('Action Figure Articulado',             'action-figure-articulado',     'Action figure genérico totalmente articulado. Compatível com escalas Marvel Legends e Star Wars Black Series.',                            55.00, 250, 115, true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/180513-action-figure-3d-model'),
('Charizard Flexi Articulado',           'charizard-flexi',              'Charizard flexível e articulado — fica de pé e tem pescoço, cauda e asas móveis. Print-in-place.',                                         65.00, 300, 135, true, true,  true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/398058-charizard-flexi-articulated-pokemon'),
('Pikachu Flexi Articulado',             'pikachu-flexi',                'Pikachu retrô articulado e flexível. Mistura nostalgia dos anos 90 com o charme dos brinquedos modernos.',                                 50.00, 220, 100, true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/618392'),
('Baby Yoda – Grogu Articulado',         'baby-yoda-grogu',              'Grogu articulado de The Mandalorian com pernas móveis. Sentado na borda da prateleira com muito estilo.',                                  60.00, 270, 120, true, true,  true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/683229-baby-yoda-grogu-articulated-no-ams-needed'),
('Pikachu Print-in-Place',               'pikachu-print-in-place',       'Pikachu posável que pode deitar, sentar e ficar de pé. Zero montagem, zero suporte. Ótimo fidget toy.',                                   45.00, 200, 90,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/445773-articulated-pikachu-print-in-place'),
('Onix Flexi Articulado – Pokémon',      'onix-flexi-pokemon',           'Onix flexível articulado que pode abrir a boca. Segmentado com juntas precisas para movimento realista.',                                  55.00, 250, 115, true, false, true, false, (SELECT id FROM categories WHERE slug = 'bonecos'), 'https://makerworld.com/en/models/398032-onix-flexi-articulated-pokemon')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- MAQUIAGEM & BELEZA
-- ============================================================
INSERT INTO products (name, slug, description, price, print_time_minutes, filament_grams, is_available, is_featured, allows_custom_color, allows_custom_size, category_id, makerworld_url) VALUES
('Porta-Pincel de Maquiagem',            'porta-pincel-maquiagem',       'Organizador estiloso para pincéis, lápis e ferramentas de maquiagem. Base estável, design minimalista.',                                  38.00, 150, 65,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/2134065-cosmetic-brush-holder-makeup-organizer'),
('Organizador de Maquiagem',             'org-maquiagem',                'Organizador com múltiplos compartimentos para batom, sombras e produtos pequenos.',                                                        42.00, 180, 80,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/418190-makeup-organizer'),
('Organizador Giratório 360°',           'org-giratorio-360',            'Organizador giratório com 4 compartimentos em alturas diferentes e rotação suave de 360 graus.',                                          55.00, 240, 110, true, true,  true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/1759230-makeup-organizer-rotating'),
('Organizador Rotativo de Maquiagem',    'org-rotativo-maquiagem',       'Porta-maquiagem rotativo com compartimentos em alturas variadas. Elegante e acessível no camarim.',                                       58.00, 260, 115, true, false, true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/2350550'),
('Organizador de Esmaltes',              'org-esmaltes',                 'Organiza esmaltes e acessórios como uma caixa de pesca — abre completamente para fácil acesso.',                                          35.00, 150, 65,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/1007821'),
('Gaveteiro Organizador de Maquiagem',   'gaveteiro-maquiagem',          'Mini gaveteiro com opções de divisórias em todos os três níveis. Modular e totalmente configurável.',                                     65.00, 300, 135, true, false, true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/958507-make-up-organizer-drawer'),
('Porta-Esmaltes Modular',               'porta-esmaltes-modular',       'Suporte modular para esmaltes com 9 encaixes. Empilhável conforme sua coleção crescer.',                                                  38.00, 160, 70,  true, false, true, true,  (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/474503-nail-polish-organizer'),
('Organizador de Maquiagem Slim',        'org-maquiagem-slim',           'Versão slim e elegante de organizador de maquiagem. Ideal para bancadas pequenas e kits de viagem.',                                      40.00, 165, 72,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/538434-makeup-organizer'),
('Bancada de Banheiro com Drenagem',     'bancada-banheiro-drenagem',    'Organizador de pia com zona de drenagem inteligente. Separa área úmida da seca para maior higiene.',                                      70.00, 340, 150, true, false, true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/2094889-ultimate-minimal-self-draining-bathroom-vanity'),
('Organizador Completo de Maquiagem',    'org-completo-maquiagem',       'Solução completa para organizar toda a maquiagem: pincéis, batons, sombras e paletas em um único objeto.',                                50.00, 220, 100, true, false, true, false, (SELECT id FROM categories WHERE slug = 'maquiagem'), 'https://makerworld.com/en/models/232650-makeuporganizer')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- BRINDES & PRESENTES
-- ============================================================
INSERT INTO products (name, slug, description, price, print_time_minutes, filament_grams, is_available, is_featured, allows_custom_color, allows_custom_size, category_id, makerworld_url) VALUES
('Chaveiro Personalizável',              'chaveiro-personalizavel',      'Chaveiro com nome ou texto personalizado gerado em cliques. Ótimo presente e brinde corporativo.',                                        18.00, 45,  10,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/1598928-customizable-keychain'),
('Chaveiro com QR Code ou Logo',         'chaveiro-qrcode-logo',         'Chaveiro com QR Code ou logotipo personalizável. Com suporte para NFC — ideal para brindes corporativos.',                                22.00, 55,  12,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/1013687-qr-code-or-logo-keychain-generator-with-nfc'),
('Porta-Marcador ou Cartão de Visita',   'porta-marcador-cartao',        'Clipe display individual para marcador de livro ou cartão de visita. Design simples e funcional.',                                        15.00, 35,  8,   true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/1304904-single-bookmark-or-business-card-holder'),
('Plaquinha Personalizada + Porta-Cartão','plaquinha-porta-cartao',      'Plaquinha de nome para mesa com porta-cartões e espaço para canetas. Ótima para presentes de escritório.',                              30.00, 90,  40,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/486879-personalized-name-plate-business-card-holder'),
('Prensa para Tags e Cartões',           'prensa-tags-cartoes',          'Mini prensa para imprimir tags de presente e cartões de visita. Área útil de 8,9 x 5 cm.',                                               45.00, 180, 80,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/17123-gift-tag-and-business-card-printing-press'),
('Porta-Cartão de Visitas',              'porta-cartao-visitas',         'Porta-cartão moderno nas versões japandi e solid. Segura cartões de até 92 mm de largura.',                                              28.00, 75,  30,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/1638512-business-card-holder'),
('Porta-Cartão Presente Namorados',      'porta-cartao-namorados',       'Porta-cartão presente print-in-place. Ideal para o Dia dos Namorados e outras datas especiais.',                                          20.00, 60,  22,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/1048095'),
('Porta-Cartão Milwaukee',               'porta-cartao-milwaukee',       'Porta-cartão inspirado no sistema Milwaukee PackOut. Espaço interno 90×50×56 mm para cartões e gift cards.',                             25.00, 65,  25,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/616524-milwaukee-business-and-gift-card-holder'),
('Display para Tags de Preço',           'display-tags-preco',           'Display para tags de preço em cartão de visita (Avery 8871). Ideal para feiras e pontos de venda.',                                       22.00, 55,  20,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/1013393'),
('Cartão de Visita 3D Paramétrico',      'cartao-visita-3d',             'Cartão de visita impresso em 3D com design paramétrico. Diferenciado e memorável para networking.',                                      18.00, 40,  8,   true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/476693-parametric-business-card'),
('Jogo da Velha Dia dos Namorados',      'jogo-velha-namorados',         'Tabuleiro de jogo da velha temático para presentear no Dia dos Namorados. Print-in-place, pronto para jogar.',                           35.00, 120, 55,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'brindes'), 'https://makerworld.com/en/models/993833')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- PERSONALIZADOS
-- ============================================================
INSERT INTO products (name, slug, description, price, print_time_minutes, filament_grams, is_available, is_featured, allows_custom_color, allows_custom_size, category_id, makerworld_url) VALUES
('Gerador de Chaveiro com Nome',         'gerador-chaveiro-nome',        'Chaveiro com nome personalizado gerado em cliques — escolha a fonte, cor e tamanho do anel.',                                              20.00, 50,  11,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'personalizados'), 'https://makerworld.com/en/models/480136-custom-name-keychain-generator'),
('Capinha de Celular Customizada',       'capinha-celular-customizada',  'Capinha de celular sob medida: informe o modelo do seu aparelho e personalizamos o design.',                                              35.00, 120, 50,  true, true,  true, false, (SELECT id FROM categories WHERE slug = 'personalizados'), 'https://makerworld.com/en/models/478570'),
('Chaveiro Articulado Personalizado',    'chaveiro-articulado-personalizado', 'Chaveiro articulado com nome personalizado em relevo. Flexível e resistente para o uso diário.',                                  25.00, 65,  15,  true, false, true, false, (SELECT id FROM categories WHERE slug = 'personalizados'), 'https://makerworld.com/en/models/1259108-articulated-keychain-with-personalized-name'),
('Chaveiro com Nome',                    'chaveiro-com-nome',            'Chaveiro moderno com nome personalizado em acabamento limpo. Ideal para presentear com toque pessoal.',                                   18.00, 40,  9,   true, false, true, false, (SELECT id FROM categories WHERE slug = 'personalizados'), 'https://makerworld.com/en/models/1481230-personalized-keychain-with-name'),
('Gerador de Placa e Nome Paramétrico',  'gerador-placa-nome',           'Placa ou letreiro personalizado com auto-escala de texto. Perfeito para quarto, escritório ou sala.',                                     35.00, 100, 40,  true, true,  true, true,  (SELECT id FROM categories WHERE slug = 'personalizados'), 'https://makerworld.com/en/models/2179735-ultimate-sign-nameplate-generator-parametric')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- IMAGENS DOS PRODUTOS (coverUrl do CDN MakerWorld)
-- ============================================================

-- Decoração
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US4a6e3930db0d0a/design/2025-03-10_3b86b11b74513.png',    'Vaso Fiori Espiral',             true, 0 FROM products WHERE slug = 'vaso-fiori-espiral'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US1f1c7b7bde3192/design/2025-01-07_7ebd52132579.png',    'Vasos Japandi',                  true, 0 FROM products WHERE slug = 'vasos-japandi'             ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US86f9ee3a854216/design/2025-04-29_b719688d445278.jpg',  'Vaso Clicker The Last of Us',    true, 0 FROM products WHERE slug = 'vaso-clicker-tlou'         ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USc59949b2f2eda5/design/2025-08-08_492b32abe6866.png',   'Castiçal Anjo Guardião',         true, 0 FROM products WHERE slug = 'castichal-anjo-guardiao'   ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US352ee87f434c2e/design/2024-02-05_4dc138508dce5.jpg',   'Luminária Pendente Art Déco',    true, 0 FROM products WHERE slug = 'luminaria-art-deco'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USb49b6cd92e7bf3/design/2025-05-02_94d786d0c071b.png',   'Vaso Pixelado Cúbico',           true, 0 FROM products WHERE slug = 'vaso-pixelado-cubico'       ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US533ef0d592bed0/design/2024-05-03_c1adeeb8f47bb.png',   'Vaso Orgânico Texturizado',      true, 0 FROM products WHERE slug = 'vaso-organico-texturizado'  ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US8f51f2d895c690/design/2025-04-20_498ef35d3797e8.jpg',  'Vaso Geométrico de Linhas',      true, 0 FROM products WHERE slug = 'vaso-geometrico-linhas'    ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USd476fe59038287/design/2025-12-28_0e1a724d9a348.jpg',   'Vaso Personalizado Tamanho Ideal', true, 0 FROM products WHERE slug = 'vaso-tamanho-ideal'       ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US2a7e76eae35d72/design/2025-01-22_a2cae970c6846.png',   'Vaso Elegante Minimalista',      true, 0 FROM products WHERE slug = 'vaso-elegante-minimalista' ON CONFLICT DO NOTHING;

-- Utilitários
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USb0aee2f62a8650/design/2023-08-29_2heg6p3b9yry.jpg',   'Organizador de Cabos Portátil',     true, 0 FROM products WHERE slug = 'organizador-cabos-portatil'     ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US6cd2acf2206584/design/2025-01-18_9dd727813dc5f.jpg',  'Organizador de Cabos',              true, 0 FROM products WHERE slug = 'organizador-cabos'              ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US603a5520109477/design/2025-11-16_ad36ae6dfc124.jpeg', 'Suporte de Cabos com Grampo',       true, 0 FROM products WHERE slug = 'suporte-cabos-grampo'           ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USc3ed71c6844ef2/design/2025-10-31_33d5a212958838.jpg', 'Clips Organizadores de Cabos',      true, 0 FROM products WHERE slug = 'clips-organizadores-cabos'      ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US3dd0fd632e7776/design/2024-06-04_28074c54ed833.png',   'Organizador de Cabos Minimalista',  true, 0 FROM products WHERE slug = 'organizador-cabos-minimalista'  ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USf84eaf71ce3961/design/2025-03-02_25808da1b7cac.png',   'Organizador de Cabos Ergonômico',   true, 0 FROM products WHERE slug = 'organizador-cabos-ergonomico'   ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US9cb3f8cd521e0c/design/44b38cd8606929a4.png',           'Organizador de Carregadores',       true, 0 FROM products WHERE slug = 'organizador-carregadores'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USdb6beef93bdca0/design/2024-03-24_2e65494fd2a95.jpg',  'Suporte de Escova Dental Mural',    true, 0 FROM products WHERE slug = 'suporte-escova-dental-mural'    ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US5e7f13ddcc0127/design/2024-03-15_298b13cc42441.png',   'Suporte Mural para Sabonete',       true, 0 FROM products WHERE slug = 'suporte-sabonete-mural'          ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/DSM00000001012342/design/2025-01-19_24b1403bf29be8.jpg', 'Porta-Escova de Dentes de Parede',  true, 0 FROM products WHERE slug = 'porta-escova-parede'            ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US9e2594317b82b0/design/2023-11-29_aab217bd353dd.jpg',  'Porta-Utensílios de Cozinha Mural', true, 0 FROM products WHERE slug = 'porta-utensilios-cozinha'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US531f3971e4bb39/design/2025-01-22_63e8c6afe7048.jpg',  'Porta-Copos com Suporte Mural',     true, 0 FROM products WHERE slug = 'porta-copos-suporte-mural'      ON CONFLICT DO NOTHING;

-- Escritório
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US899d9c028786fd/design/c8ca2f592564a2d9.jpg',          'Organizador de Mesa Escritório',     true, 0 FROM products WHERE slug = 'org-mesa-escritorio'          ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USc67485efc26daa/design/2024-12-04_ee477e7cc4da.jpeg',  'Suporte Celular + Porta-Caneta',     true, 0 FROM products WHERE slug = 'suporte-celular-porta-caneta' ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US1931ce138981cc/design/2025-01-16_238810626cb66.jpg',  'Organizador com Dock para Celular',  true, 0 FROM products WHERE slug = 'org-dock-celular'            ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US7a158683b9e98/design/2025-04-01_bc63ad00d8359.jpg',   'Organizador Mesa com Suporte',       true, 0 FROM products WHERE slug = 'org-mesa-suporte'             ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/DSM00000000864633/design/2024-12-09_9a1b7b586db31.jpg', 'Organizador com Gaveta e Dock',      true, 0 FROM products WHERE slug = 'org-gaveta-dock'              ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USddb67d2f12b946/design/2025-08-23_13f90ceddc365.png',  'Organizador com Suporte Integrado',  true, 0 FROM products WHERE slug = 'org-suporte-integrado'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USdd2653b0efae50/design/2025-12-12_1e2788b4699e08.png', 'Sistema Modular iPhone + Canetas',   true, 0 FROM products WHERE slug = 'sistema-modular-iphone'       ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US7e99c14a339383/design/2024-12-20_e3d30781bce3.jpg',   'Organizador Slim com Dock',          true, 0 FROM products WHERE slug = 'org-slim-dock'                ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US686c0dde21fb70/design/2024-09-17_b6e2ff10fb6d.jpg',   'Organizador Magnético Modular',      true, 0 FROM products WHERE slug = 'org-magnetico-modular'         ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US116ba4dc0cb091/design/2024-10-15_5566635ea4945.jpg',  'Organizador Design Moderno',         true, 0 FROM products WHERE slug = 'org-design-moderno'           ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US130462633dc2df/design/8281e29dc7aa43cc.png',          'Organizador com 3 Gavetas',          true, 0 FROM products WHERE slug = 'org-3-gavetas'                ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US4c9e551193d252/design/2025-11-21_2c2c9b1a411098.jpg', 'Organizadores Empilháveis',          true, 0 FROM products WHERE slug = 'organizadores-empilaveis'     ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US9e45127a8ff7f4/design/9039746b70426dcf.png',          'Sistema Modular Personalizado',      true, 0 FROM products WHERE slug = 'sistema-modular-personalizado' ON CONFLICT DO NOTHING;

-- Games
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USd851cf91a3249a/design/2025-05-07_9789464d764fb.jpg',  'Suporte Xbox + Fone de Ouvido',       true, 0 FROM products WHERE slug = 'suporte-xbox-headphone'   ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US5ada36a7e9e4f0/design/2025-01-28_a001261eb0922.jpg',  'Suporte Gamer Futurista',             true, 0 FROM products WHERE slug = 'suporte-gamer-futurista'  ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USe4d207907b647e/design/2024-12-20_30b86a48ac54f.jpg',  'Suporte para Headset com Bandeja',    true, 0 FROM products WHERE slug = 'suporte-headset-bandeja'  ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US304750fd498909/design/2025-10-28_81fed0a13df1a.png',  'Torre de Games com Pegboard',         true, 0 FROM products WHERE slug = 'torre-games-pegboard'     ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US74c7b4398050bd/design/2025-08-15_9b4cae25b1f88.png',  'Torre de Games Empilhável',           true, 0 FROM products WHERE slug = 'torre-games-empilaveis'   ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US5f982e34e2fedf/design/2025-03-02_75131726905d7.png',  'Porta de Masmorra DnD',               true, 0 FROM products WHERE slug = 'porta-masmorra-dnd'       ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US86d39b9bd84f77/design/2024-11-20_cd5a7a13a817d.jpg',  'Torre de Dados Castelo Medieval',     true, 0 FROM products WHERE slug = 'torre-dados-castelo'      ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US5c9f1015c36146/design/2024-06-19_00cefae24ae33.webp', 'Torre de Dados Isengard LOTR',        true, 0 FROM products WHERE slug = 'torre-dados-isengard'     ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/DSM00000000110167/design/2023-12-27_8c5cefcd3e7f3.jpg', 'Torre de Dados de Viagem',            true, 0 FROM products WHERE slug = 'torre-dados-viagem'       ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US68fa614548e71d/design/2025-06-21_f3e5a061a37508.jpg', 'Torre de Dados Caveira Fantasia',     true, 0 FROM products WHERE slug = 'torre-dados-caveira'      ON CONFLICT DO NOTHING;

-- Bonecos
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USd21608aad63db2/design/2024-11-08_dc30f1af7af75.jpg',  'Dragão Floppy Flexi Articulado',   true, 0 FROM products WHERE slug = 'dragao-floppy-flexi'           ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USf83603e3274d49/design/2025-06-24_bb5372609606d.png',  'Dragão Rise com Imãs',             true, 0 FROM products WHERE slug = 'dragao-rise-imas'              ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US1df0ed57882545/design/2025-07-27_1b075570d1bef.jpg',  'Banguela Night Fury Articulado',   true, 0 FROM products WHERE slug = 'banguela-night-fury'           ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USfc798616b17b98/design/2024-01-05_ea6e4cfb2c08a8.png', 'Dragão de Cristal Articulado',     true, 0 FROM products WHERE slug = 'dragao-cristal-articulado'     ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USc7aeba603a6550/design/b2840cfdf3d531c8.jpg',          'Shenron Articulado Dragon Ball',   true, 0 FROM products WHERE slug = 'shenron-dragon-ball'           ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USf1c9af7469ff8c/design/2025-03-07_228a49d0aa829.jpg',  'Rathalos Monster Hunter Dragon',   true, 0 FROM products WHERE slug = 'rathalos-monster-hunter'       ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US9aca0a64349126/design/2026-01-04_27c8a5da33ce3.png',  'Dragão Fofo Articulado',           true, 0 FROM products WHERE slug = 'dragao-fofo-articulado'         ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/DSM00000001174730/design/2025-03-10_233d495f91b8b.png', 'Stormtrooper Star Wars',           true, 0 FROM products WHERE slug = 'stormtrooper-star-wars'         ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USb389f3cf863317/design/2025-09-24_37121a0c4857e8.jpeg', 'MaidTrooper Star Wars',           true, 0 FROM products WHERE slug = 'maidtrooper-star-wars'          ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USa2965d1ec90c55/design/2024-02-10_350698d57a8ec.png',  'Action Figure Articulado',         true, 0 FROM products WHERE slug = 'action-figure-articulado'       ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US43a1853333c059/design/2025-02-27_c2b544e0ec1f2.jpg',  'Charizard Flexi Articulado',       true, 0 FROM products WHERE slug = 'charizard-flexi'               ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USf145cb27005a58/design/2024-09-02_5e325d92b2f74.jpg',  'Pikachu Flexi Articulado',         true, 0 FROM products WHERE slug = 'pikachu-flexi'                 ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USec925833daa67e/design/2024-10-05_176f4fb87ca98.jpg',  'Baby Yoda Grogu Articulado',       true, 0 FROM products WHERE slug = 'baby-yoda-grogu'               ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US5a00b5465a0b7f/design/2024-04-28_48f03773a03bd.jpg',  'Pikachu Print-in-Place',           true, 0 FROM products WHERE slug = 'pikachu-print-in-place'         ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US5933fe104ca414/design/2024-11-19_6e532a7219837.jpg',  'Onix Flexi Articulado Pokémon',    true, 0 FROM products WHERE slug = 'onix-flexi-pokemon'            ON CONFLICT DO NOTHING;

-- Maquiagem
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USce15461a15ef9/design/c5978614dcf8a6c8.jpg',           'Porta-Pincel de Maquiagem',           true, 0 FROM products WHERE slug = 'porta-pincel-maquiagem'      ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US3515891d23e608/design/2024-04-07_8b57e8f5c326c8.png', 'Organizador de Maquiagem',            true, 0 FROM products WHERE slug = 'org-maquiagem'               ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US388b77030dcfc5/design/2025-09-03_247c7dcd5bc0d.jpg',  'Organizador Giratório 360°',          true, 0 FROM products WHERE slug = 'org-giratorio-360'           ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US4a416084db7298/design/69cd9e9affee17c2.jpg',          'Organizador Rotativo de Maquiagem',   true, 0 FROM products WHERE slug = 'org-rotativo-maquiagem'      ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US19edc4e0a1ff57/design/2025-01-18_cb9b2ecd0f7a9.jpg',  'Organizador de Esmaltes',             true, 0 FROM products WHERE slug = 'org-esmaltes'                ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/DSM00000000958507/design/2025-01-27_b217169387a3d.jpg', 'Gaveteiro Organizador de Maquiagem',  true, 0 FROM products WHERE slug = 'gaveteiro-maquiagem'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/DSM00000000474503/design/2024-05-25_5a8df83079d4b.jpg', 'Porta-Esmaltes Modular',              true, 0 FROM products WHERE slug = 'porta-esmaltes-modular'      ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US1f9a19cd82fe20/design/2025-03-05_c706e17ce38ab.jpg',  'Organizador de Maquiagem Slim',       true, 0 FROM products WHERE slug = 'org-maquiagem-slim'          ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US9a337224b537b5/design/2025-12-09_17ae8a07fa3f48.png', 'Bancada de Banheiro com Drenagem',    true, 0 FROM products WHERE slug = 'bancada-banheiro-drenagem'   ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/DSM00000000232650/design/2024-03-06_f447b9b9b143c8.jpg', 'Organizador Completo de Maquiagem',  true, 0 FROM products WHERE slug = 'org-completo-maquiagem'     ON CONFLICT DO NOTHING;

-- Brindes
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US2d290f7ee50719/design/2025-07-17_e57882e9da67c.jpg',  'Chaveiro Personalizável',            true, 0 FROM products WHERE slug = 'chaveiro-personalizavel'     ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USb0aee2f62a8650/design/2023-08-29_2heg6p3b9yry.jpg',   'Chaveiro com QR Code ou Logo',       true, 0 FROM products WHERE slug = 'chaveiro-qrcode-logo'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USdc7b86dff250f4/design/2025-04-10_5725400e65f2a.jpg',  'Porta-Marcador ou Cartão de Visita', true, 0 FROM products WHERE slug = 'porta-marcador-cartao'       ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US4f9aa2fa660110/design/2024-06-06_a02b829f7d41.png',   'Plaquinha Personalizada + Cartão',   true, 0 FROM products WHERE slug = 'plaquinha-porta-cartao'      ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US3ce67ab1470229/design/2023-09-23_9xk78ldndo85.jpeg',  'Prensa para Tags e Cartões',         true, 0 FROM products WHERE slug = 'prensa-tags-cartoes'         ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US9fa031a7d60302/design/2025-07-25_57b151dc1b178.png',  'Porta-Cartão de Visitas',            true, 0 FROM products WHERE slug = 'porta-cartao-visitas'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USa41bb45566e026/design/2025-01-28_a3d20dbbdc4b4.jpg',  'Porta-Cartão Presente Namorados',    true, 0 FROM products WHERE slug = 'porta-cartao-namorados'      ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US4fbecdf455be76/design/2024-08-31_72c2b8bb56eb4.jpg',  'Porta-Cartão Milwaukee',             true, 0 FROM products WHERE slug = 'porta-cartao-milwaukee'      ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US6a3cb1f07681da/design/2025-01-19_eb83816208ff2.jpeg', 'Display para Tags de Preço',         true, 0 FROM products WHERE slug = 'display-tags-preco'          ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USf62e8027aceb3c/design/2024-05-30_2afee199b746a.png',  'Cartão de Visita 3D Paramétrico',    true, 0 FROM products WHERE slug = 'cartao-visita-3d'            ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/DSM00000000993833/design/2025-01-14_24a327b74e0478.jpg', 'Jogo da Velha Dia dos Namorados',   true, 0 FROM products WHERE slug = 'jogo-velha-namorados'        ON CONFLICT DO NOTHING;

-- Personalizados
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USc657761faebbc6/design/2024-07-01_71c40da168d44.png',  'Gerador de Chaveiro com Nome',        true, 0 FROM products WHERE slug = 'gerador-chaveiro-nome'              ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USd5cf1b34255342/design/2024-05-30_2ee858c9393d7.jpg',  'Capinha de Celular Customizada',      true, 0 FROM products WHERE slug = 'capinha-celular-customizada'        ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/USc281d49d9a6350/design/2025-03-28_8a8265241dda4.jpg',  'Chaveiro Articulado Personalizado',   true, 0 FROM products WHERE slug = 'chaveiro-articulado-personalizado' ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/US3b61c92a363e4f/design/32c9fbe1fb2f4de8.webp',        'Chaveiro com Nome',                   true, 0 FROM products WHERE slug = 'chaveiro-com-nome'                  ON CONFLICT DO NOTHING;
INSERT INTO product_images (product_id, url, alt, is_primary, sort_order) SELECT id, 'https://makerworld.bblmw.com/makerworld/model/UScdca03ba68b7bc/design/f400336e3f93a687.jpg',          'Gerador de Placa e Nome Paramétrico', true, 0 FROM products WHERE slug = 'gerador-placa-nome'                ON CONFLICT DO NOTHING;
